services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: szkot
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
    - "3307:3306"
    volumes:
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - backend

  web:
    build: ./app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: szkot
    ports:
      - "5000:5000"
    networks:
      - backend

  updater:
    build: ./mysql/python_scripts
    depends_on:
      - db
    networks:
      - backend
    restart: always


networks:
  backend: